name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-20.04
    steps:
      - name: checkout master
        uses: actions/checkout@v2
      - name: python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: configure remote for deployment
        run: |
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email ${GITHUB_ACTOR}@users.noreply.github.com
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}
      - name: mkdocs install
        run: pip3 install -r requirements.txt
      - name: mkdocs deploy
        run: mkdocs gh-deploy --force
